{% set version = '0.2.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-anomalydetection
  version: {{ version|replace("-", "_") }}

source:
  fn: anomalyDetection_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/anomalyDetection_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/anomalyDetection/anomalyDetection_{{ version }}.tar.gz
  sha256: e127eefdd9db3c83624dd1779d4f026e66430a164b0074fa58f113f03b585c8c

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: gplots, knitr, RColorBrewer, rmarkdown, testthat,
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-mass
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-caret
    - r-dplyr
    - r-ggplot2
    - r-gmp
    - r-magrittr
    - r-plyr
    - r-purrr
    - r-tibble
    - r-tidyr
    - libopenblas                # [osx]

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-rcpp >=0.12.11
    - r-rcpparmadillo
    - r-caret
    - r-dplyr
    - r-ggplot2
    - r-gmp
    - r-magrittr
    - r-plyr
    - r-purrr
    - r-tibble
    - r-tidyr
    - libopenblas                # [osx]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('anomalyDetection')"           # [not win]
    - "\"%R%\" -e \"library('anomalyDetection')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/koalaverse/anomalyDetection
  license: GPL (>= 2)
  summary: Implements procedures developed by Gutierrez et al. (2017, <https://journal.r-project.org/archive/2017/RJ-2017-039/index.html>)  to
    aid in detecting network log anomalies. By combining various multivariate  analytic
    approaches relevant to network anomaly detection, it provides cyber  analysts efficient
    means to detect suspected anomalies requiring further evaluation.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: anomalyDetection
# Type: Package
# Title: Implementation of Augmented Network Log Anomaly Detection Procedures
# Version: 0.2.5
# Authors@R: c(  person("Bradley", "Boehmke", email = "bradleyboehmke@gmail.com", role = c("aut", "cre")), person("Brandon", "Greenwell", email = "greenwell.brandon@gmail.com", role = c("aut")), person("Jason", "Freels",  email = "auburngrads@live.com",  role = c("aut")),  person("Robert", "Gutierrez",  email = "rjgutierrez2015@gmail.com",  role = c("aut")) )
# Maintainer: Bradley Boehmke <bradleyboehmke@gmail.com>
# Date: 2018-02-24
# Description: Implements procedures developed by Gutierrez et al. (2017, <https://journal.r-project.org/archive/2017/RJ-2017-039/index.html>)  to aid in detecting network log anomalies. By combining various multivariate  analytic approaches relevant to network anomaly detection, it provides cyber  analysts efficient means to detect suspected anomalies requiring further evaluation.
# URL: https://github.com/koalaverse/anomalyDetection
# BugReports: https://github.com/koalaverse/anomalyDetection/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 2.10)
# Imports: caret, dplyr, ggplot2, gmp, magrittr, MASS, plyr, purrr, Rcpp (>= 0.12.11), stats, tibble, tidyr,
# RoxygenNote: 6.0.1
# Suggests: gplots, knitr, RColorBrewer, rmarkdown, testthat,
# LinkingTo: Rcpp, RcppArmadillo
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2018-03-07 14:32:09 UTC; bradboehmke
# Author: Bradley Boehmke [aut, cre], Brandon Greenwell [aut], Jason Freels [aut], Robert Gutierrez [aut]
# Repository: CRAN
# Date/Publication: 2018-03-07 16:18:12 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
