# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lFUB2dODduJDHlsa06Ggs1ShoG4nUhrQ4ZqOTwzYzaX2SvEhuneRNs7fqiYPwXMrh32K0Os+cG426tfy+yxFcbY8LvRBlz9+d2jQY3e7WoVbd5QjaFR2bYJCk9jK+V12C7qRvXmqae5NAO31XRc1kNtzSnW0+EAltjgPR93dtCv6qgP75RydsOaFyZgghHdGyVwyVFZ4sZWWWTJQRuVH1A5fZI4DZiiGei+yuxvobiQ8QEZf3o5ZhECPUZ2gp6m1MTIvHQtyEPanPk+Skr7MHRjpj8kvsojIHCAh0Rk9vsGgD5iKwk77sEsx3vLQgWJm5Nyhw2OSpytGozAEI8Fx0Y4NN7f0gMm3m8KzIorjRipIrgRIBvcSILTaGWCkqzpb1mFyH0freTaTUPjQfkqDQhejlLG6EtpTbDfmfdUYsJ4lp4qrb9SKUSCg14O4zhOJeYwQiCJOR4n2qFOb+mPmoZCSsuFCKeliif91loeh9cUf5tHqID47CJAxqzsX5iQQHzcnaywfAHLIVPPARqhYj8cuYuhFRZjYTlpBmsyXiwIq+TK2I2PZXu9GeQHjYFbo6hjJnO+dJkFoglv1cAsKVs4aCOI1Epb55Ig0+MVOLxw3WweOshzOXUpvZdAyLmaKwH3CkbIptrodR03GYIN+f3pdrsnE2k2zgkrJ3degHI8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
