travis:
  secure:
    BINSTAR_TOKEN: lFUB2dODduJDHlsa06Ggs1ShoG4nUhrQ4ZqOTwzYzaX2SvEhuneRNs7fqiYPwXMrh32K0Os+cG426tfy+yxFcbY8LvRBlz9+d2jQY3e7WoVbd5QjaFR2bYJCk9jK+V12C7qRvXmqae5NAO31XRc1kNtzSnW0+EAltjgPR93dtCv6qgP75RydsOaFyZgghHdGyVwyVFZ4sZWWWTJQRuVH1A5fZI4DZiiGei+yuxvobiQ8QEZf3o5ZhECPUZ2gp6m1MTIvHQtyEPanPk+Skr7MHRjpj8kvsojIHCAh0Rk9vsGgD5iKwk77sEsx3vLQgWJm5Nyhw2OSpytGozAEI8Fx0Y4NN7f0gMm3m8KzIorjRipIrgRIBvcSILTaGWCkqzpb1mFyH0freTaTUPjQfkqDQhejlLG6EtpTbDfmfdUYsJ4lp4qrb9SKUSCg14O4zhOJeYwQiCJOR4n2qFOb+mPmoZCSsuFCKeliif91loeh9cUf5tHqID47CJAxqzsX5iQQHzcnaywfAHLIVPPARqhYj8cuYuhFRZjYTlpBmsyXiwIq+TK2I2PZXu9GeQHjYFbo6hjJnO+dJkFoglv1cAsKVs4aCOI1Epb55Ig0+MVOLxw3WweOshzOXUpvZdAyLmaKwH3CkbIptrodR03GYIN+f3pdrsnE2k2zgkrJ3degHI8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
