travis:
  secure:
    BINSTAR_TOKEN: EdjY0YrT7ui17mYGsDYESxb0ynf9gT4wtPPvUqsFUh9TpuqvZQSJ1Ap3YUzEEP1ZvGeK/KBu2tE62aBkZ/RqD59wd+znN4Ewt/gfS/qw/48Yt6QuYcq8+YFcJENlEkkatUSe7myrL3ofoOm9xqsbkcpmp2mzSRZA7QRiQc1x00ejlEXmM46W9iqKnWeaL+AbvEASrPidH9QTMdMmHytXv70XEIfD5bQNnaqx4XdhGgARtQ7k+PpdWiieqNNY6/2pstA+mH5j3ujQFkUaKgDlhezij9k4Pky8yPImuaO6TWistoXXXsWw3RlIGMucxgFdpAQa6i++bLjJ5H6wBLCNb7GlpPdYGq0LLQZubKtzdxs1UtpG2K1YQJS2CSwtSPbvS/rlfjPY7y/DcRbEnnM/+r9lGcGavByy3V20wGwQnsW4mwXJY6C/joAvCH/QTM1TZLR/C8Lt6mGUj3437L+6VWd623zA7+jYUby1Q+Khk7H1ZeOQVOvvqxEtTPyQeoTIosw0Rq4JY/LHwQq8RhLyCVyruhXor/CfIk3KY3Pq7ZUCBEz7+VclccxXVwrw7DX2rNmxegtIRNMWb9YO16vP2dhjP9Yczv73gUVWJjBawsKjI80mJnUvOoJKu4MPa4QrmuELclaxS/tX5KxZc4hUdYwUn00w7hvZ0pke5459k9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
