travis:
  secure:
    BINSTAR_TOKEN: QEbpfvudnVqmk6EJbhoosgMwz+iGYBBsxsS0U3ioFMQYPBhehUMzyou/xrcw3i33J/yQa/ix5JAqeXe5BPnV3ehHaKFsG1Mtpl/RJ9cNUCzIgOheCV3ms4g4pAVCpjS2NvYZdx3yjql7c8cJJGl/DqZ8Xn7WBoVtO6oiM7j8IX74zN7gtnltdPwng7E7EhQizo4oBIk5uqN2hEXExS64/qbtEjd32B8hlxpoHhLic7giR5CmYYSdrqK6vBIULuija2xoVjJR8bMSO1l7K4JlrCc4sPEtFiPd8gzDskhtq5W/Hv7YEzyhY+bpMVW89TeesjsSAPa6Jv0NPsprKdi2a00bwmzu+dnQgdEYtewwDAJAQIVjrORJOM1fTciUWMdG/LHnZMWPU3Y5ah/+tZ/ybF2Nr1FOGAUdq+LGwjpome1ZF1yj8B/Zgtj5FyaYQ27bsQl/A0Q6MiByeCDv9SbAJwthgzyBcLCP6NnM6GxXefNo5g5ZKhwt3ASTyyE7a3yxQ4V0cT4H9fHnZ6ETmIGaVeZXleMcI3G6xP64QFWurOKJ8RF2tJaDmZUyaBIMHL+6Q1tklYZPvoijdzMehGZyE5UH0wqwZOT3ERvZdaqJfxuFDAN3wGjA3A/AxKPWIMNcB0XeBvk30WPSCvw+56jnwf53+sXouE7YfzF3HtHtsRU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
